@extends('layouts.app')
@push('css')
<style>

</style>
@endpush
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-9 offset-md-1" style="margin-top: 2%">
            <div class="box ml-4 mr-3">

                <p class="h2 mt-2" style="color:#135040;">E-commerce</p><br>
                <img class="card-img-top" src="{{ secure_asset('storage/1 E-commerce.jpeg') }}">
                <p class="MsoNormal" style="margin-top: -50px;text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;">&nbsp;</p>
                <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;">&nbsp;</p>
                <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12pt;">When you k</span><span style="font-size: 12pt;">now your market</span><span lang="EN-PH" style="font-size: 12pt;">, you&rsquo;ve </span><span style="font-size: 12pt;">set your business</span><span lang="EN-PH" style="font-size: 12pt;"> up</span><span lang="EN-PH" style="font-size: 12pt;"> </span><span lang="EN-PH" style="font-size: 12pt;">to lead, innovate and win</span><span style="font-size: 12pt;">. </span><span lang="EN-PH" style="font-size: 12pt;">With our industry-standard market reports, you&rsquo;ll get an in-depth look at what delights your customers, what advantages you have over your competitors, and what </span><span style="font-size: 12pt;">you can do to capitalize on industry trends.</span></p>
                <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12pt;">Growth is something that Shopify </span><span style="font-size: 12pt;">excels in. After an inevitable slump in the first quarter of 2020, they were able to grow their second quarter revenue by 97%. </span><span lang="EN-PH" style="font-size: 12pt;">One of its strengths is its content library dedicated to helping entrepreneurs with their business. In their article about market research, they wrote: <em>&ldquo;Especially for retailers just starting out, it may feel like a lot of decisions are made on guesswork or instinct. Market research can remove much of that uncertainty.&rdquo; </em></span></p>
                <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span style="font-size: 12pt;">Etsy</span><span lang="EN-PH" style="font-size: 12pt;"> was just a budding website that focused on being an online marketplace for artisans. They steadily grew by word-of-mouth and they </span><span style="font-size: 12pt;">found that a </span><span lang="EN-PH" style="font-size: 12pt;">growing number of visitors accessing their site through mobile devices. They saw this as a</span><span style="font-size: 12pt;"> great</span><span lang="EN-PH" style="font-size: 12pt;"> opportunity</span><span style="font-size: 12pt;"> for expansion.</span><span lang="EN-PH" style="font-size: 12pt;"> So in 2011, they launched the Etsy app for iPhone. In the first 4 months, they reached 1 million downloads. The iPad and Android versions of the app soon followed. In 2013, they reported that mobile visits had increased 244%.</span></p>
                <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12pt;">eBay, a pioneer in the e-commerce industry, highly recommends market research as part of their sellers&rsquo; growth strategy. They go on to say on their website, <em>&ldquo;Detailed business analysis sets most successful sellers apart.&rdquo;</em> </span><span style="font-size: 12pt;"><span style="mso-spacerun: yes;">&nbsp;</span>eBay is currently making a strong effort to let customer data drive innovations for their platform in order to offer a more intuitive shopping experience. </span></p>
                <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span style="font-size: 12pt;">Alibaba</span><span lang="EN-PH" style="font-size: 12pt;"> gathered</span><span lang="EN-PH" style="font-size: 12pt;"> </span><span lang="EN-PH" style="font-size: 12pt;">from their research that</span><span style="font-size: 12pt;"> Chinese consumers had become increasingly tech savvy</span><span lang="EN-PH" style="font-size: 12pt;">, yet</span><span lang="EN-PH" style="font-size: 12pt;"> </span><span lang="EN-PH" style="font-size: 12pt;">a vast majority </span><span style="font-size: 12pt;">were still adamant on having credit cards. The</span><span lang="EN-PH" style="font-size: 12pt;">y found a way to connect those findings and turn it into a solution. In 2004, they introduced </span><span style="font-size: 12pt;">Alipay, a digital payment app that made online transactions simple and accessible to just about anyone. Alibaba&rsquo;s CEO Jack Ma had been initially mocked for th</span><span lang="EN-PH" style="font-size: 12pt;">is</span><span style="font-size: 12pt;"> model, but he was convinced that </span><span lang="EN-PH" style="font-size: 12pt;">Alipay</span><span lang="EN-PH" style="font-size: 12pt;"> </span><span lang="EN-PH" style="font-size: 12pt;">would be able to</span><span style="font-size: 12pt;"> earn his customers&rsquo; trust. As of August 2020,</span><span style="font-size: 12pt;"> </span><span style="font-size: 12pt;">Alipay has generated $17 trillion in payments. </span></p>
                <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph;"><span lang="EN-PH" style="font-size: 12pt;">For</span><span lang="EN-PH" style="font-size: 12pt;"> </span><span lang="EN-PH" style="font-size: 12pt;">Amazon CEO Jeff Bezos</span><span style="font-size: 12pt;">,</span><span lang="EN-PH" style="font-size: 12pt;"> market research was the basis on which his company developed their infamous &ldquo;customer obsessed&rdquo; culture. </span><span style="font-size: 12pt;">Bezos</span><span lang="EN-PH" style="font-size: 12pt;">&rsquo; strategy aimed to </span><span style="font-size: 12pt;">provide a seamless and customized online shopping experien</span><span lang="EN-PH" style="font-size: 12pt;">ce that used market data and</span><span style="font-size: 12pt;"> consumer metric</span><span lang="EN-PH" style="font-size: 12pt;">s. Because of this, they&rsquo;ve </span><span style="font-size: 12pt;">created several</span><span lang="EN-PH" style="font-size: 12pt;"> industry-disrupting </span><span style="font-size: 12pt;">features</span><span lang="EN-PH" style="font-size: 12pt;"> on their platform</span><span style="font-size: 12pt;"> like </span><span lang="EN-PH" style="font-size: 12pt;">the</span><span style="font-size: 12pt;"> price comparison tool and prime delivery</span><span lang="EN-PH" style="font-size: 12pt;">. This was the key </span><span style="font-size: 12pt;">that turned his </span><span lang="EN-PH" style="font-size: 12pt;">basic</span><span style="font-size: 12pt;"> online bookstore into </span><span lang="EN-PH" style="font-size: 12pt;">a $1 trillion</span><span style="font-size: 12pt;"> e-commerce juggernaut. </span></p>
            </div>
        </div>
        <div class="col-md-9 offset-md-1" style="margin-top: 2%">
            <div class="box ml-4 mr-3">

                <p class="h2 mt-2" style="color:#135040;">Technology</p><br>
                <img class="card-img-top" src="{{ secure_asset('storage/2 Technology.jpeg') }}">
                <p class="MsoNormal mt-4" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">The </span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">New York Times</span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> report</span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">ed</span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> that </span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">tech companies are currently dominating the stock market because they&rsquo;ve become an indispensable facet of our everyday lives.</span><em><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> </span></em><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">We</span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">&rsquo;</span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">re here to provide </span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">you with </span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">valuable </span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">market </span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">reports </span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">on</span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> computer hardware and networking, software, </span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">IT, and </span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">telecommunications,</span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> so your business can capitalize on the monumental opportunities in this industry. </span></p>
                <p class="MsoNormal mt-2" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">When Google </span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">launched the #LookBeforeYouLeave campaign to promote Google Maps in India</span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">,</span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> </span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">t</span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">hey crafted a</span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> </span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">relevant marketing campaign that</span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> highlighted</span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> what they found out was</span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> a major pain-point for their potential users: traffic. They also took advantage of media that they found out was the most accessible to their target audience: TV and Youtube. With their informed marketing strategy, t</span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">he campaign drove a 40% increase of daily active users</span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> </span><span style="font-size: 12pt; line-height: 115%; font-family: SimSun;">－</span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> a</span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> huge win for Google</span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;"> in India</span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">.</span></p>
                <p class="MsoNormal mt-2" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">Telecommuncation service leader AT&amp;T emphasizes that data is a company&rsquo;s most important asset. Armed with the knowledge that there was high demand for faster and more reliable mobile internet connectivity,&nbsp; AT&amp;T invested heavily in its 5G network service. This savvy move will not only cater to the needs of the market, but will also open up a host of future business opportunities for the forward-thinking company. </span></p>
                <p class="MsoNormal mt-2" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">In Adobe&rsquo;s case, they had been very successful with their licensed software programs</span><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">, b</span><span lang="EN-PH" style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">ut the industry were shifting towards a cloud-based subscription service model. Adobe knew that adjusting to these changes was going to be a long, arduous and costly transition. In order to survive and stay competitive, they had to follow the demands of their market. This decision proved to be Adobe&rsquo;s most profitable. In 2017, subscriptions made up 86% of their $7.3 billion revenue. </span></p>
                <p class="MsoNormal mt-2" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span style="font-size: 12pt; line-height: 115%; font-family: Garamond, serif;">Apple is now considered the world&rsquo;s first $2 trillion company. This comes as a result of shifting their priorities from hardware to software services which includes iTunes, App Store, Apple Pay and AppleCare. Adding to this is the release of their highly-anticipated 5G iPhone. Their beloved products have been designed with a meticulous focus on the needs of their users, and knowing their market there&rsquo;s more opportunities for growth in a world running on smartphones. </span></p>
                <p class="MsoNormal mt-2" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;">&nbsp;</p>
            </div>
        </div>
        <div class="col-md-9 offset-md-1" style="margin-top: 2%">
            <div class="box ml-4 mr-3">

                <p class="h2 mt-2" style="color:#135040;">Service Industries</p><br>
                <img class="card-img-top" src="{{ secure_asset('storage/3 Service Industries.jpeg') }}">
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">We make sure that our insights can be leveraged to your advantage. We cater to all types of service-based businesses, from financial services to professional services, and everything in between. You can expect premium research </span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black;">reports</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;"> that will help </span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black;">you </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">provide the kind of quality service deserving of customer loyalty. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">At a time where more banks are closing down in favor of digital platforms, JPMorgan Chase plans to bring in 400 more brick-and-mortar branches in 15-20 new markets in the next 5 years. After finding out that people still preferred to visit banks for assistance in loans and mortgages, JPMorgan Chase branches will be providing digital solutions and pairing it with excellent customer service. Not only will this initiative serve to improve the economy of low to moderate income communities, but will also help JPMorgan and Chase reach their goal of an additional 80 million customers by 2022. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">Accenture continues its market studies with regards to the alarming cost of cybercrime throughout multiple industries. With this in mind, they&rsquo;ve recently been acquiring several cybersecurity companies to provide more innovative solutions for their clients. In 2020, they&rsquo;ve reported that 65% of their recent bookings comes from their digital, cloud and cybersecurity services.</span></p>
                <p class="MsoNormal"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; mso-bidi-font-family: Garamond; color: black; mso-ansi-language: EN-PH;">Starbucks finds itself in a market saturated by a fleet of copycat competitors offering more impressive products. Despite the odds, the Seattle coffee shop is still miles ahead because of their distinctive customer experience honed by trend data and consumer feedback. This focus on building authentic relationships with their customers is one of the the main reasons why Starbucks is patronized in more than 29,000 stores throughout 72 countries. </span></p>
                <p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">Recently, McDonald&rsquo;s rolled out their Velocity Growth Plan because of the insights they&rsquo;ve gained from their market research data. They&rsquo;ve made several major changes to their brand which reflects this customer-centric growth strategy. This plan includes modernizing the design of their restaurants, adapting digital kiosks, improving their mobile app, building its delivery platform, and taking action on social and environmental issues. Because of the successful execution of their Velocity Growth Plan, Mcdonald&rsquo;s systemwide sales crossed the $100 billion threshold for the first time. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; mso-bidi-font-family: Garamond; color: black; mso-ansi-language: EN-PH;">Hilton&rsquo;s marketing strategies are based on customer feedback and data. When they launched their &ldquo;Expect Better, Expect Hilton&rdquo; campaign to deepen their relationship with their younger guests, they grounded this effort on the insight that most of these travelers are confused by comparing hotel prices and perks. Hilton now offers a price match guarantee tool that comes with several perks when guests book through their website or app. </span></p>
            </div>
        </div>
        <div class="col-md-9 offset-md-1" style="margin-top: 2%">
            <div class="box ml-4 mr-3">

                <p class="h2 mt-2" style="color:#135040;">Heavy Industries</p><br>
                <img class="card-img-top" src="{{ secure_asset('storage/4 Heavy Industries.jpeg') }}">
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">Whether your business is engaged in </span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black;">Energy, Manufacturing, Chemicals, </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">Materials,</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black;"> Transportation</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">, or </span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black;">Shipping</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">, we will provide comprehensive findings and significant perspectives that are relevant to your growth strategies.<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span></span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">On their site, General Electrics claims that <em>&ldquo;customers are on the front lines of the world's toughest industrial challenges.&rdquo;</em> This encapsulates their belief that the feedback their customers give to them has driven their push for revolutionary industry practices that are socially and environmentally conscious.</span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">Ford is bringing market research into the forefront. Car manufacturers have typically been influenced by manufacturing costs during their product development and marketing phase. Commendably, Ford is making a serious commitment to hav</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black;">e </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">better discussions with their customers through</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black;"> market research</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">. By adopting driver-assisted technologies and eco-friendly vehicles, they&rsquo;ve shown that they&rsquo;re listening and the results have been paying off. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">With the world population expected to go up to 9 billion in the next 2 decades, ExxonMobil is faced with the difficult balancing act of catering to the world&rsquo;s growing energy demands while also heeding public </span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black;">concern over</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;"> global warming. According to their 2019 annual report, they&rsquo;ve already dedicated $10 billion on research and technology that will address climate change. To date, their measures have resulted in eliminating more than 400 million tonnes of CO</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; mso-bidi-font-family: Garamond; color: black; mso-ansi-language: EN-PH;">&sup2;</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">-equivalent emissions. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">Maersk, the world&rsquo;s largest container shipping firm, is also facing similar issues. Their market research also forecasts a sharp decline for the demand of oil and coal by 2025. They&rsquo;ve already invested $60 million in zero emission vessels that will be commercially viable by 2030. They also plan to go carbon-neutral by 2050. </span></p>
            </div>
        </div>
        <div class="col-md-9 offset-md-1" style="margin-top: 2%">
            <div class="box ml-4 mr-3">

                <p class="h2 mt-2" style="color:#135040;">Life Sciences</p><br>
                <img class="card-img-top" src="{{ secure_asset('storage/5 Life Sciences.jpeg') }}">
                <p class="MsoNormal" style="margin-top: 12.0pt;text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black;">Pharmaceutical and Life Sciences industry succeeds in today&rsquo;s age of digitalization through the implementation of various IT solutions. </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">We offer market studies</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black;"> </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">which will</span><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black;"> open avenues for new products and better practices</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;"> that will significantly improve the quality of life of many.</span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt;text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">Diabetes has afflicted more than 34 million people in America. Abbot </span><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black;">addresses this by launching </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">the FreeStyle Libre</span><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black;"> 2</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">, a device that makes continuous blood glucose monitoring painless, accessible and significantly more affordable. The broad-based healthcare company has uniquely positioned itself as one of the pioneers in a market that&rsquo;s expected to rise to $13 billion by 2023. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt;text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">Pfizer has realized that they urgently need</span><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black;">ed</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;"> to re-imagine their old delivery practices. To</span><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black;"> anticipate </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">the heightened variation of needs in their marketplace</span><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black;">,</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;"> they now make a point of analyzing their market place twice a year through strategic customer targeting and segmentation. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt;text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">Johnson &amp; Johnson </span><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black;">are also </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">finding new models for product development. They now emphasize on listening to the demands of their customer and meeting those demands in real time</span><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black;"> like they did when their consumers were asking for a travel-sized version of Listerine. </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">They&rsquo;ve also taken into careful consideration, the presentation and sustainability of their packaging which they found largely affects consumers&rsquo; brand perception.<span style="mso-spacerun: yes;">&nbsp; </span></span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt;text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">Healthcare and drugstore company CVP is continually working on overhauling the entire medical records system starting with their mobile app. Executive Vice President, Stephen Gold, explains: <em>&ldquo;The data shows that our prescription benefit management members who are using ScriptSync have improved their adherence anywhere from 6% to 10%. And statistics show that if the national adherence rate was increased by just 1 percentage point, it would generate $6 billion of health-care savings a year.&rdquo; </em>CVP currently sits near the top of the Forbes 500 list. </span></p>
            </div>
        </div>
        <div class="col-md-9 offset-md-1" style="margin-top: 2%">
            <div class="box ml-4 mr-3">

                <p class="h2 mt-2" style="color:#135040;">Public Sector</p><br>
                <img class="card-img-top" src="{{ secure_asset('storage/6 Public Sector.jpeg') }}">
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">Monitoring current social, economic, technological</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-bidi-font-weight: bold;">,</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;"> and political trends is integral for public service. We provide our clients with relevant data to inform policies, services, campaigns and interventions for our clients in education, government agencies and contractors, real estate and housing, non-profits, and religious organizations. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">In Massachusetts, deaths caused by drug overdose were rising by an alarming 65% in 2014 compared to 2012. The Department of Public Health commissioned five research agencies to understand the opioid crisis in the state. As a result of their findings, Massachusetts passed Chapter 52 of the Acts of 2016. This law outlines a wide range of holistic provisions that shifts opioid addiction from a criminal justice issue into a public health matter. By 2017, the Bay State reported that opioid-related deaths fell by over 8%, the first decrease seen in half a decade. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">The American Red Cross launched a campaign to combat the worrying decline of blood donations. This effort led to the research and development of their innovative mobile app. The app makes the process of blood donation easier and more emotionally rewarding by allowing users to track their donations. The award winning app soon achieved more than 1 million downloads, helped save thousands of lives, and brought in $80 million for the Red Cross charity.</span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">In the U.K., the Salvation Army had already established a solid direct marketing strategy, but they still needed more donors for their annual Christmas fundraiser. Through three years of market research, they were able to retain the patronage of previous donors through their mailing campaign. They also effectively used TV to reach out to an audience that was ten years younger than their current donor demographic. In all, they achieved their goal of higher donation volume while also maintaining a high return of investment. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">Coursera, a University-based online learning platform, saw a decline in post-New Year student retention. After conducting several research studies and tests, they discovered that external factors like jobs, family matters, and vacations played a major part in distracting their students from completing their courses. Keeping these in mind, Coursera redesigned their curriculum to include peer assistance, accountability measures, and milestone tracking. With this format, Coursera was able to find a middle ground between accessibility and high student retention. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">Lockheed Martin Corp., a trusted defense contractor for the American government, was looking to boost its sales through the help of the country&rsquo;s allies. To do this, they&rsquo;ve been monitoring international geopolitical security challenges, undertaking various cost reduction initiatives, establishing joint ventures, and investing in pioneering hypersonic technology. All these strategies have undoubtedly improved its profitability in a potential trillion dollar market. </span></p>
            </div>
        </div>
        <div class="col-md-9 offset-md-1" style="margin-top: 2%">
            <div class="box ml-4 mr-3">

                <p class="h2 mt-2" style="color:#135040;">Media</p><br>
                <img class="card-img-top" src="{{ secure_asset('storage/7 Media.jpeg') }}">
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">With so many people consuming content through more platforms than ever before, it&rsquo;s no wonder brand marketers are saying, &ldquo;Attention is the new currency.&rdquo; To assists our clients involved in traditional, print and digital media, we provide research solutions for market trends and forecasts, marketing strategies and effectiveness, branding, audience studies, competitor evaluation, and more.</span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">Recognizing the value of market research, the top name in trade publishing, Penguin Random House, has developed their own consumer data portal. Their findings are used to improve publishing and marketing campaigns for their authors. In their case study, they had used their insights to boost traction for a historical novel they were promoting. By letting their research influence their second-wave marketing campaign, the book maintained its standing in the New York Times bestseller list well into its first year.</span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">The foundations of Disney&rsquo;s Marvel franchise was built upon an already loyal fanbase from its comic book days. By studying their market and developing a long-term strategy for drawing out their superheroes through standalone films, they allowed time for a new audience to develop a personal bond with th</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-bidi-font-weight: bold;">eir</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;"> characters. This method also brought Marvel Studios into prominence along the way. Once the storylines </span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-bidi-font-weight: bold;">were interwoven </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">with one another, it created a compounding effect that led to Disney experiencing its greatest triumph in 2019. Its crowning achievement was <em>Avengers: End Game </em>which drew $2.797 billion in the box office and is now the highest grossing film of all time. </span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">In a similar way, HBO gained insights from their market back when DVDs were threatening the survival of TV companies. At that </span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-bidi-font-weight: bold;">point</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">, TV shows presented self-contained stories per episode to cater to fickle channel surfers. To capitalize on the &lsquo;avid viewers&rsquo; that DVDs fostered, HBO took a risk on producing <em>The Sopranos</em> </span><span style="font-size: 12.0pt; line-height: 115%; font-family: SimSun; mso-bidi-font-family: SimSun; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">－</span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;"> a story that told a complex, cinematic narrative throughout a series of episodes. The show&rsquo;s critical and commercial success opened up a new business model for HBO. This was the same principle that made Game of Thrones such an unprecedented global phenomenon.</span></p>
                <p class="MsoNormal" style="margin-top: 12.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 115%; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 115%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">Netflix started as a DVD distribution company back in 1997. But as more people were watching shows off the internet, Netflix jumped at the chance to innovate the online streaming platform. They enticed their customers by buying the licenses of beloved movies and TV shows, and then charging a cheap price for a monthly subscription. This strategy worked so well that they were able to produce their own must-see shows that were only available on their platform. Netflix now has a total of 192.95 million subscribers worldwide and is currently the #1 contributor of internet traffic. </span></p>
            </div>
        </div>
        <div class="col-md-9 offset-md-1" style="margin-top: 2%">
            <div class="box ml-4 mr-3">

                <p class="h2 mt-2" style="color:#135040;">Retail and Consumer</p><br>
                <img class="card-img-top" src="{{ secure_asset('storage/8 Retail and Consumer.jpeg') }}">
                <p class="MsoNormal" style="margin-top: 12.0pt;text-align: justify; text-justify: inter-ideograph; vertical-align: baseline;"><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH;">Technological revolutions, changing consumer behaviors, and geopolitical relationships have drastically changed the face of the industry. Whether our clients are in Retail and Wholesale, Apparel, Luxury goods, or Food and Beverage, we will create up-to-date and insightful data reports that will help future-proof any business.</span></p>
                <p class="MsoNormal"><span lang="EN-PH" style="margin-top: 12.0pt;font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; mso-bidi-font-family: Garamond; color: black; mso-ansi-language: EN-PH;">Nike weathers through disruptions in the market by proactively adopting disruptive strategies. For example, Nike Live is an innovative concept store that couples data-driven in-store experiences with exceptional customer service. The store also acts as a complement to their NikePlus subscription service available through their app. NikePlus keeps track of preferences and buying habits so their members can enjoy personalized product offers and discounts. With this kind of commitment to customer experience, t</span><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; mso-bidi-font-family: Garamond; color: black;">here&rsquo;s no wonder why </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; mso-bidi-font-family: Garamond; color: black; mso-ansi-language: EN-PH;">Nike </span><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; mso-bidi-font-family: Garamond; color: black;">is </span><span lang="EN-PH" style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; mso-bidi-font-family: Garamond; color: black; mso-ansi-language: EN-PH;">widely considered the most valuable apparel brand in the world. </span></p>
                <p class="MsoNormal"><span lang="EN-PH" style="margin-top: 12.0pt;font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; mso-bidi-font-family: Garamond; color: black; mso-ansi-language: EN-PH;">With luxury fashion houses facing the economic downturn, it&rsquo;s no secret they&rsquo;re all setting their sights on China. China makes up about 33% of the world&rsquo;s luxury goods purchases and that number is expected to reach 50% in the next couple of years. Competition between heritage brands is fierce, but Louis Vuitton currently reigns supreme in the mainland. They&rsquo;ve achieved this by doing their due diligence on research. Unlike most of their competitors, LV is appealing to a much younger demographic, they&rsquo;ve created a strong social media presence, and they&rsquo;ve been conscientious to local regulations and customs. </span></p>
                <p class="MsoNormal"><span lang="EN-PH" style="margin-top: 12.0pt;font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; color: black; mso-ansi-language: EN-PH; mso-bidi-font-weight: bold;">Coke is one of the most recognizable brands in the world, but they noticed a disconnnect between themselves and the younger demographic when they were developing a new marketing campaign in Australia. They found that people there tended to reject large corporate brands. Their ingenious counter for this was to harnessing the power of personalization. They launched the &lsquo;Share A Coke&rsquo; campaign in 2011 which swapped the iconic Coke logo with a person&rsquo;s first name. It worked so well in Australia that it eventually became a massively successful global campaign. </span></p>
                <p class="MsoNormal"><span lang="EN-PH" style="margin-top: 12.0pt;font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; mso-bidi-font-family: Garamond; color: black; mso-ansi-language: EN-PH;">Cargill, one of the top producers and distributors of agricultural products in the world, isn&rsquo;t allowing itself to get complacent. Cargill&rsquo;s Assistant Vice President,<em> </em>Chris Pardey,</span><span style="font-size: 12.0pt; line-height: 107%; font-family: 'Garamond',serif; mso-bidi-font-family: Garamond; color: black;"> stated that climate change and unforeseeable natural disasters could take away the progress they&rsquo;ve built. <span style="mso-spacerun: yes;">&nbsp;</span>He goes on to mention that when a business invests in research, the impact of that decision would still be of consequence even after two decades. </span></p>
                <p class="MsoNormal">&nbsp;</p>
                <p class="MsoNormal">&nbsp;</p>
            </div>
        </div>
    </div>
    @push('js')
    <script>
        $(document).ready(function() {
            $('.reviews').slick({
                dots: true,
                infinite: true,
                speed: 300,
                slidesToShow: 1,
                adaptiveHeight: true
            });
            $('.center').slick({
                centerMode: true,
                centerPadding: '20px',
                slidesToShow: 3,
                responsive: [{
                        breakpoint: 768,
                        settings: {
                            arrows: false,
                            centerMode: true,
                            centerPadding: '40px',
                            slidesToShow: 3
                        }
                    },
                    {
                        breakpoint: 480,
                        settings: {
                            arrows: false,
                            centerMode: true,
                            centerPadding: '40px',
                            slidesToShow: 1
                        }
                    }
                ]
            });
        });
    </script>
    @endpush
    @endsection
